### ISSUE TITLE
更新 autoprefixer

### ISSUE THREAD

**Issue by nighca** [Front-End-Engineering-Cloud/builder#110]
目前执行 `fec-builder generate -e production` 会提示

```
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
```

较老版本的 browserslist（2.x）是由 autoprefixer 引入的，考虑升级 autoprefixer。

参考 [autoprefixer changelog](https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md)，8.0 使用 browserslist@3.x，9.0 使用 browserslist@4.x

**Comment by surmon-china** [comment]
#126 

browserslist 4.x
autoprefixer 9.x

**Comment by nighca** [comment]
这个在 #125 （对应版本 [v1.17.0](https://github.com/Front-End-Engineering-Cloud/builder/releases/tag/v1.17.0)）已经解决了
