### ISSUE TITLE
exclude:ts部分

### ISSUE THREAD

**Issue by yueyongxidain** [Front-End-Engineering-Cloud/builder#115]
# 我只发现有对js做转换范围控制  builder/lib/webpack-config/addons/add-transform.js 234行左右。但是并没有针对ts做控制，目前我遇到的情况是ts包里面有一些代码规范问题，我不想针对ts包做转换操作 fec-builder 无法操作

* 我希望能够对ts做范围控制，否则我这边不能做镜像打包了 @

**Comment by nighca** [comment]
@yueyongxidain 针对 js 做转换范围控制是因为：

> builder 默认会跳过对依赖包 Javascript 内容的转换，以提升构建效率

JavaScript 是比较特殊的内容，特点是“原则上”经过 bundle 后（无须特别 loader 处理）就能在浏览器环境运行；所以“跳过对依赖包 Javascript 内容的转换，以提升构建效率”是常见的构建性能优化手段；TypeScript 内容不会做这样的处理，因为：

1. 一个 TypeScript 实现的 package 有义务在自身发布的时候进行构建，并以 JavaScript 的形式发布，所以理论上我们不会用到 `node_modules` 中的 TypeScript 内容，除非开发时（对应的 TypeScript 内容也是我们自己维护的包，link 进来方便调试）
2. TypeScript 内容不经过处理（转换）的话没法在浏览器环境里运行的，所以如果你忽略了，那项目应该是没法正常跑的

我不太清楚你的情况是具体什么样的
