### ISSUE TITLE
支持 babel-plugin-import

### ISSUE THREAD

**Issue by raychenfj** [Front-End-Engineering-Cloud/builder#117]
支持 babel-plugin-import

https://github.com/ant-design/babel-plugin-import

优化 antd lodash 等包的加载方式，按需加载

**Comment by nighca** [comment]
@raychenfj 不太想集成这个东西；

* 一方面理论上项目自己能添加这个 plugin 也能配置
* 另一方面需要这个插件是因为 tree-shaking 能力的 break，所以我觉得解决这个问题的正确思路应该是去让 tree-shaking 正常工作，方案参考 https://webpack.js.org/guides/tree-shaking/

**Comment by raychenfj** [comment]
> 一方面理论上项目自己能添加这个 plugin 也能配置

那么 builder 有配置项能添加插件么？

**Comment by nighca** [comment]
@raychenfj builder 目前自己没有插件机制，不过 babel plugin 可以的，项目自己安装对应 plugin，然后通过对 transformer `babel` 进行配置使用这个 plugin 就好

![image](https://user-images.githubusercontent.com/1492263/68012969-9381eb00-fcc6-11e9-8ebd-82e6068a294c.png)

比如这里是配置 preset 的示例
