### ISSUE TITLE
polyfills 的一些问题

### ISSUE THREAD

**Issue by huangbinjie** [Front-End-Engineering-Cloud/builder#123]
正好打算排查下 portal-kodo 的 polyfills 冲突的问题，然后发现这边的实现有点问题。

### `@babel/runtime-corejs2` 没必要

1、runtime 已经有依赖 corejs2
2、没用到

### `@babel/polyfills` 没必要

1、废弃
> Since @babel/polyfill was deprecated in 7.4.0, we recommend directly adding core-js and setting the version via the corejs option.

我们的版本 `"@babel/core": "^7.6.2"`

2、重复导入冲突

> NOTE: Only use import "core-js"; and import "regenerator-runtime/runtime"; once in your whole app. If you are using @babel/polyfill, it already includes both core-js and regenerator-runtime: importing it twice will throw an error. Multiple imports or requires of those packages might cause global collisions and other issues that are hard to trace. We recommend creating a single entry file that only contains the import statements.

### `@babel/plugin-transform-runtime` 没必要

这个插件2个目的：

1、抽出内置的 helper 方法，比如 __assign __extends。这个还有点用，能减少 2kb。

2、避免全局污染，全局污染对第三方库不友好(会污染主项目)。然而从结果上看我们是需要全局注入(污染有贬义..)的。

我觉得这两个目的应该不是 #112 打算考虑的？

### `@babel/preset-env` 不需要开启关于 polyfills 的配置

接 #122 

正如上面分析的，既然使用全局的，那 useBuiltIns 默认 false 没问题，即不处理。

## 怎么处理 polyfills

不清楚全局注入是否有讨论过。
如果打算不打算全局注入就用 `@babel/plugin-transform-runtime` 就好了。
如果全局注入，继续使用小马之前的写法改一下就好了
```js
new VirtualModulesPlugin({
  [
    path.join('./', srcDir, '/') + mockFile
  ]: (
    `require('core-js')`
  )
})
```

## 动态组件那边怎么处理

我觉得使用 `@babel/plugin-transform-runtime` 转换成不污染全局的编译方式比较好，从这个角度看 builder 应该是要 `@babel/plugin-transform-runtime` 但是需要一个可配置项？

**Comment by huangbinjie** [comment]
@surmon-china @nighca 求看看，好像有点复杂

**Comment by doxiaodong** [comment]
@babel/plugin-transform-runtime  这个方式我觉得好一点，现在有些仓库会自动引入 helper 的一些方法。

**Comment by Luncher** [comment]
> @babel/runtime-corejs2 没必要
> @babel/polyfills 没必要
> @babel/plugin-transform-runtime 没必要
> @babel/preset-env 不需要开启关于 polyfills 的配置

那么 `polyfill` 怎么实现呢？

>@babel/polyfill

这个包官方说是废弃了，但是需要注意的是，如果是用 `core-js@2` , `entry` 的模式 [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry)，还是依赖于 `@babel/polyfill`:
>NOTE: When using core-js@2 (either explicitly using the corejs: 2 option or implicitly), @babel/preset-env will also imports and requires of @babel/polyfill. This behavior is deprecated because it isn't possible to use @babel/polyfill with different core-js versions.


>@babel/runtime-corejs2 没必要
>1、runtime 已经有依赖 corejs2
>2、没用到

`@babel/plugin-transform-runtime` 依赖于 `@babel/runtime-corejsx`。`@babel/runtime-corejsx` 等于：
+ runtime helpers
+ regenerator-runtime
+ core-js@x

如果用 `@babel/plugin-transform-runtime` 的方式来做 `polyfill`，这个包还是需要的。

>正如上面分析的，既然使用全局的，那 useBuiltIns 默认 false 没问题，即不处理。

+ `builder` 里面 [preset-env](https://github.com/Front-End-Engineering-Cloud/builder/blob/master/lib/webpack-config/addons/add-transform.js#L57) 和 [transform-runtime](https://github.com/Front-End-Engineering-Cloud/builder/blob/master/lib/webpack-config/addons/add-transform.js#L72) 的 `polyfill` 都配置了，当前 `builder` 的`useBuiltIns` 配置是 `entry`，而不是 `false`. 两个同时开启 `polyfill` 确实是不推荐的做法：
![image](https://user-images.githubusercontent.com/5138977/79777120-5ccd8900-8369-11ea-928b-1ddfab556824.png)

+ 只所以提这个 [pr](https://github.com/Front-End-Engineering-Cloud/builder/pull/122), 原因也在 `pr` 上面说了，个人觉得 `transform-runtime` 的方式好一些..

>不清楚全局注入是否有讨论过。
>如果打算不打算全局注入就用 @babel/plugin-transform-runtime 就好了。
>如果全局注入，继续使用小马之前的写法改一下就好了...

貌似仅仅 `require('core-js')` 是不够的，还需要 [regenerator-runtime](https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime)。另外也没有了 ` re-use of Babel's injected helper code to save on codesize` 的好处。

**Comment by nighca** [comment]
补充下 7.4 的信息 https://babeljs.io/blog/2019/03/19/7.4.0

**Comment by huangbinjie** [comment]
我上面的结论都是基于「确定全局注入是适合我们的方案」的基础上提出的改法...

如果打算用 `transform-runtime` 实现确实看起来更好点，能同时满足动态组件那边的需求。

@Luncher

**Comment by surmon-china** [comment]
#126

**Comment by nighca** [comment]
should be fixed by #126
