### ISSUE TITLE
替换 babel-loader 为 esbuild-loader

### ISSUE THREAD

**Issue by yinxulai** [Front-End-Engineering-Cloud/builder#136]
`esbuild` 的编译速度无需多言
如果可以替换目前的  `babel-loader` 为 `esbuild-loader` 理论上可以大大提升构建的速度

**Comment by nighca** [comment]
@yinxulai 版本号 0.12.16 真的敢用吗？

**Comment by nighca** [comment]
esbuild 还不成熟，issue 先关了，等比较成熟（至少发布 1.0.0）之后再重新评估

**Comment by nighca** [comment]
https://swc.rs/ 这个好像比 esbuild 还成熟一点，Next.js 11.1 已经用它替代 babel & terser 了

https://nextjs.org/blog/next-11-1#adopting-rust-based-swc
