### ISSUE TITLE
getStaticPath function ERROR

### ISSUE THREAD

**Issue by doxiaodong** [Front-End-Engineering-Cloud/builder#35]
应该是

```
const getStaticPath = conf => path.resolve(getDistPath(conf), conf.staticDir)
```

**Comment by nighca** [comment]
这个就是希望获得项目根目录下 `static` 目录的路径的。

主要是考虑支持很多前端项目把一些静态内容直接放 `static`（有的是`public`下），然后希望这个目录下的内容不被处理直接被发布的场景。不过这个功能还没有实现，主要是也还没有这样的前端项目接入，要求这样的功能。

你这里是想要拿到 `dist/static` 这个路径来用嘛？

**Comment by doxiaodong** [comment]
那就是要 copy 的功能了
