### ISSUE TITLE
图片压缩

### ISSUE THREAD

**Issue by doxiaodong** [Front-End-Engineering-Cloud/builder#38]
目前默认的图片使用 `file-loader` 引入，在实际中应当再加上 `image-webpack-loader` 以压缩图片

**Comment by doxiaodong** [comment]
我的想法是加入一个 `picture` transform 来做，你看怎么样

**Comment by doxiaodong** [comment]
@nighca

**Comment by nighca** [comment]
@doxiaodong 先前留过一个字段 [`optimization`](https://github.com/Front-End-Engineering-Cloud/builder/blob/master/preset-configs/default.json#L44)，我想着所有对逻辑没影响的优化都可以放这里做，是不是这个可以做进来，通过类似：

```json
{
  "optimization": {
    "image-compression": ...
  }
}
```

这样来开启？

因为还没有开始这么做，我也不确定这种把对逻辑无影响的优化跟 transform 分开的做法是不是有好处，你看呢

**Comment by doxiaodong** [comment]
我是觉得不好做，当进入到 transform.file 的时候，用什么来判断是 picture 呢，只有图片才要优化

**Comment by nighca** [comment]
后缀名？

**Comment by doxiaodong** [comment]
不太合适呀，后缀本身就是要配在 transform 里的，通过 transform 来匹配怎么处理，现在又反过来，感觉不合适

**Comment by nighca** [comment]
transformer 的定位偏业务逻辑一点，决定了输入的内容格式跟输出的内容格式；而是不是压缩这个事情既不影响输入内容格式，也不影响输出内容格式，如果单独做一个 `picture`，对应“做了压缩的”图片的 `file` 类 transform，那么对于其他的可能会用于图片资源的 transform 行为（比如 data url、svg sprite 这些），就也需要对应的新的 transformer，比如 data-url-picture，svg-sprite-picture，就不是特别合适了。所以我觉得这个行为不应该用新的 transformer 来实现。

如果是做成 transformer 本身的配置，我觉得也可以接受，比如：（`compress` 的默认值可以就是 `true`，表示在 `production` 环境会尝试对资源做压缩，至于怎么压缩，自动根据文件后缀名去判断，然后去尝试）

```json
{
  "png": {
    "transformer": "file",
    "config": {
      "compress": true
    }
  }
}
```

做在 transformer 的坏处是，会有一堆可以配置的地方（可能几乎每个 transformer 都需要控制资源是不是压缩的配置项），看起来有点繁琐，而单独有一个关于性能优化的 `optimization` 相关的配置，看上去好像会清晰一点。

**Comment by doxiaodong** [comment]
这个也行

**Comment by nighca** [comment]
@doxiaodong 那就先按做成 transformer 本身配置的方式来搞吧

**Comment by nighca** [comment]
fixed in #71
