### ISSUE TITLE
soucemap 可配置

### ISSUE THREAD

**Issue by doxiaodong** [Front-End-Engineering-Cloud/builder#69]
beta 环境需要 soucemap 和  prod 环境不需要 soucemap

**Comment by yanhao1991** [comment]
希望能把这个配置放到 build-config.json 中，我们 prod 环境也需要 sourcemap，需要上传到 sentry 里做错误解析
@nighca

**Comment by nighca** [comment]
@yanhao1991 生产环境生成 sourcemap 稍微有点风险：一般来说 sourcemap 应该尽量避免给用户接触到；所以要么需要在部署到线上前把里边的 sourcemap 筛掉，要么需要配置服务器把 sourcemap 文件的访问筛掉。

我想这么着去处理：生产环境也生成独立的 sourcemap 文件，但是上传 CDN（现在上传 CDN 也是 builder 干的）的时候跳过这些文件，即，这些 sourcemap 文件只能通过构建的结果包拿到，线上 CDN 不能拿到；你看怎么样？

**Comment by yanhao1991** [comment]
@nighca 嗯，的确不应该上传CDN，我们也只需要拿到sourcemap文件，单独保存下来就好

**Comment by nighca** [comment]
https://github.com/Front-End-Engineering-Cloud/builder/releases/tag/v1.9.0
