### ISSUE TITLE
与时俱进

### ISSUE THREAD

**Issue by doxiaodong** [Front-End-Engineering-Cloud/builder#75]
webpack@4, 和 @babel@7.

**Comment by nighca** [comment]
hhh

**Comment by zhohon** [comment]
@doxiaodong webpack4 也开始意识到要简化配置, 这项目还有优势吗

**Comment by doxiaodong** [comment]
@zhohon ， 他只是简化20%约定配置，这个项目是集成99%的功能

**Comment by nighca** [comment]
@zhohon 终极目标是消灭 dev deps（甚至包括 lint test 等），构建本身规范化（对比 golang 的工具链），服务化，所以除了简化配置，还有还多事情需要做。

**Comment by doxiaodong** [comment]
https://github.com/Front-End-Engineering-Cloud/builder/issues/77 这里有些相近的

**Comment by doxiaodong** [comment]
@zhohon  ，https://github.com/doxiaodong/mobx-di
你把这个告诉付老师，我之前跟他提到过

**Comment by zhohon** [comment]
@doxiaodong 好的. 我理解的还有点浅, 我要学习下你们的代码.

**Comment by nighca** [comment]
不知道 webpack4 的话常见 loader/plugin 支持咋样了

**Comment by nighca** [comment]
fix in #131
