### ISSUE TITLE
干掉 scss 吧！

### ISSUE THREAD

**Issue by nighca** [Front-End-Engineering-Cloud/builder#88]
经常因为它导致 builder 安装失败...

**Comment by doxiaodong** [comment]
哈哈，sass 那个源码真是很难下下来，但是scss用的挺多的。

**Comment by nighca** [comment]
有没有选择安装的说法？

**Comment by doxiaodong** [comment]
不过你那里不是用 image 的么

**Comment by nighca** [comment]
开发用 npm 包，发布才用 docker

**Comment by wangkechun** [comment]
peerDependencies?

**Comment by nighca** [comment]
@wangkechun 嗯，是指类似的手段，不过现在看 `peerDependencies` 语义上不并不是“可选”，不满足会报 warning...[`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) 可能更合适一点，不过它是自动尝试去安装，而不是用户手动控制

**Comment by doxiaodong** [comment]
可不可以 自定义一个字段，然后在 postinstall 的时候根据 config 安装

**Comment by doxiaodong** [comment]
就是加一个命令， postinstall ，然后分析 build-config.json 里有没有 scss，less，这样的配置，然后按需安装，不过这个会安装到当前目录，怎么保证不写进当前项目的的 package.json 。

**Comment by nighca** [comment]
这个做不到啊，builder 的定位目前是全局安装的

**Comment by doxiaodong** [comment]
做个插件？ builder-plugin-qiniu

**Comment by nighca** [comment]
哈哈，很牛逼了，我先改 optionalDependencies 吧，至少装不上不影响整体

**Comment by doxiaodong** [comment]
还有 image-loader 的依赖也很难下。

**Comment by nighca** [comment]
是的

**Comment by codingstar** [comment]
我发现有个安全问题，node-sass 依赖的 node-gyp 一直不更新发布，有人都弃用 gulp-sass 了😂
https://github.com/nodejs/node-gyp/issues/1717#issuecomment-485741564
所以我也觉得是不是可以干掉 scss 😂或者是不是可以用 sass 代替 node-sass
