### ISSUE TITLE
可不可以在运行时重新加载 build-confg.json

### ISSUE THREAD

**Issue by codingstar** [Front-End-Engineering-Cloud/builder#93]
RT。有时候开发的时候需要修改 build-config 的配置（devProxy神马的），每次都要重启下 fec-builder，时间会很长，可不可以提供一个在运行时按一个什么键，然后就重新加载 build-config 的功能？（会不会快一点😂）

**Comment by wangkechun** [comment]
devProxy 自己跑个nginx转发就可以随时改了，或者 

https://github.com/cortesi/devd

https://caddyserver.com/docs/proxy

**Comment by lzfee0227** [comment]
> devProxy 自己跑个nginx转发就可以随时改了

架空 devProxy 的方法当然有很多，但是那样子 fec-builder 用起来就太不方便了，作为一个相对完整的 cli 工具集成度不够高

@wangkechun

**Comment by nighca** [comment]
fixed in #133
